language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ghozt81nl/dockercicd -f Dockerfile.dev .

script:
    - docker run -e CI=true ghozt81nl/dockercicd npm run test